In [20]:
import numpy as np

In [22]:
#One dimensional array
a = np.array([1,2,3,4])
#Two dimensional array
b = np.array([ [1,2],[3,4] ])
#Three dimensional array
c = np.array([ [ [1,2],[3,4] ] , [ [5,6],[7,8] ] ])

print("This is One dimensional Array")
print(a)
print("This is Two dimensional Array")
print(b)
print("This is Three dimensional Array")
print(c)

This is One dimensional Array
[1 2 3 4]
This is Two dimensional Array
[[1 2]
 [3 4]]
This is Three dimensional Array
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [25]:
#To display 3 in these arrays
print(a[2])
print(b[1][0])
print(c[0][1][0])

3
3
3


In [27]:
#To print the dimensions of arrays
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


In [28]:
#To print the structure of an array
print(a.shape)
print(b.shape)
print(c.shape)

(4,)
(2, 2)
(2, 2, 2)


In [29]:
#To print the total number of elements in array
print(a.size)
print(b.size)
print(c.size)

4
4
8


In [30]:
#To make an array till a number 
x = 10
d = np.arange(x)
print(d)

[0 1 2 3 4 5 6 7 8 9]


In [32]:
#To make an array from starting number to an ending number
starting_num = 10
ending_num = 20
e = np.arange(starting_num,ending_num)
print(e)

[10 11 12 13 14 15 16 17 18 19]


In [33]:
#To make an array from starting number to an ending number with jumps
starting_num = 10
ending_num = 100
jump = 5
f = np.arange(starting_num,ending_num,jump)
print(f)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [34]:
#Changing the order of arrays in random manner
a1 = np.random.permutation(a)
b1 = np.random.permutation(b)
c1 = np.random.permutation(c)
d1 = np.random.permutation(d)
e1 = np.random.permutation(e)
f1 = np.random.permutation(f)

print(a1)
print(b1)
print(c1)
print(d1)
print(e1)
print(f1)

[4 2 1 3]
[[3 4]
 [1 2]]
[[[5 6]
  [7 8]]

 [[1 2]
  [3 4]]]
[4 6 5 0 1 9 2 8 3 7]
[18 10 12 15 16 17 11 14 19 13]
[15 45 65 60 70 20 40 10 30 50 25 95 55 90 80 75 35 85]


In [37]:
#To create a random number between two numbers
starting_num = 10
ending_num = 20
np.random.randint(starting_num,ending_num)

18

In [39]:
#To generate an array of "n" Random numbers between 0 and 1
n = 10
g = np.random.rand(n)
print(g)

[0.50271658 0.12069313 0.49390866 0.45734544 0.25805988 0.75770742
 0.02051792 0.93413066 0.39915521 0.27363079]


In [41]:
#To generate a "m" dimensional of "n" elements Array of Random numbers between 0 and 1
m = 2
n = 3
h = np.random.rand(2,n)
print(h)

[[0.00191187 0.18436719 0.2018674 ]
 [0.11184529 0.71950412 0.39531446]]
